version: '3'

services:
  db:
    image: postgres:15
    restart: always
    container_name: cliente_dbhost
    environment:
      - POSTGRES_DB=cliente_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
